### ISSUE TITLE
Run with puppeter

### ISSUE THREAD

**Issue by hosseind88** [percy/exec-action#19]
Hi
we are using percy and puppeter for visual tests, as your sample you just wrote the way to run tests with cypress
but I want to run it with puppeter
but I don't know what it the correct way

it is my yaml file:
```
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: npm i
      - name: Percy
        uses: percy/exec-action@v0.3.0
        with:
          command: "npm run test-visuals"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```

and it is the result of test:

<img width="1139" alt="Screen Shot 2020-10-04 at 12 28 57 PM" src="https://user-images.githubusercontent.com/72156162/95011384-2f397b00-063d-11eb-8306-cf1c36b86d49.png">

it fails because I should start the server to run project then run tests, but it gives me different error on that situation
my test script is this:

```"test-visuals": "percy exec -p 40300 -- jest tests/screenshots/analytics/QuickStats.test.ts"```
