### ISSUE TITLE
Which files are required to make this work "in someone's own repo"?

### ISSUE THREAD

**Issue by Pomax** [percy/exec-action#21]
Due to business requirements, some repos can only run github-sanctioned or even only local actions: which files are required in order to make this action work by placing it in a repo's own `.github/actions/` dir?

(and ideally, can that information be added as a README.md section, to have that knowledge concisely available in a single, obvious place =)

**Comment by Robdel12** [comment]
Hey @Pomax! I'm not quite sure I understand what you're looking for. Are you looking to clone this repos source into your own repo and then use it that way? If so, you could clone the repo and then provide a path (kind of like this: https://github.com/percy/exec-action/blob/master/.github/workflows/pr.yml#L12)

**Comment by Pomax** [comment]
No, just looking to copy only exactly the files needed into the `./github/actions` dir. After some digging, it turns out this just needs to be the `action.yml` file and the `dist/index.js`, so we have [the following dir structure](https://github.com/mozilla/foundation.mozilla.org/tree/master/.github/actions/percy-exec) now:

```
+ .github
|   + workflows
|   + actions
|   |   + percy-exec
|   |      + action.yml
|   |      + index.j
```

with action.yml updated to point to `./index.js` instead of the dist dir, and our CI yml updated to say:

```yml
...
    - name: Percy Test
      uses: ./.github/actions/percy-exec
      with:
        command: "npm run cypress:ci"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
