### ISSUE TITLE
Build not triggering on GitHub PRs

### ISSUE THREAD

**Issue by akashnimare** [percy/exec-action#24]
I have installed the Percy in my repo and also using the GitHub action to get the check-in the PR itself -

My yaml script -
```
name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: 'cypress run'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```

Error log -
```sh
23s
Run percy/exec-action@v0.3.1
  with:
    command: cypress run
    working-directory: ./
    passthrough: false
    silence: false
    verbose: false
  env:
    PERCY_TOKEN: ***
/usr/local/bin/npx percy exec -- cypress run

[percy] Error: command not found "cypress"
Error: The process '/usr/local/bin/npx' failed with exit code 127
```
