### ISSUE TITLE
Very little info on how to migrate to Percy CLI

### ISSUE THREAD

**Issue by SimonDanisch** [percy/exec-action#29]
From the readme:

>⚠️ This action is only required if you're using an older SDK not using Percy CLI. In Percy CLI, GitHub actions will work out of the box.

From the [docs](https://docs.percy.io/docs/github-actions):
 
>Now you can run your tests with Percy (typically percy exec -- [test command]) and send builds to Percy from CI.

So from that I take, I shouldn't be using this anymore:
```
- name: Percy Upload
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npx percy upload ./images"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
But it doesn't really say what I should do instead...
From the docs I take I understand I can just do something like:
```
- name: Percy Upload
        run: percy upload ./images
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
But that doesn't work...
So what's the snippet I should use these days for the newest Percy CLI?
